markdownSlides:
#  image: busybox:latest
  stage: deploy
  script:
    - echo "copy images..."
    - cp slides/*.png slides/*.jpg slides/*.svg /var/www/courses.fmsoft.cn/plzs/assets -f
    - echo "copy HTML files..."
    - cp slides/*.html /var/www/courses.fmsoft.cn/plzs/ -f
    - echo "copy markdown files..."
    - cp slides/*.md /var/www/courses.fmsoft.cn/plzs/gitlab/ -f
    - echo "done"
  only:
    refs:
      - main
    changes:
      - slides/*

